language: go
go_import_path: github.com/SUSE/saptune
go:
  - 1.7.x
os:
  - linux
sudo: required
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
#- sudo -E env "PATH=$PATH" go test -v -cover ./...
#- go build
